[build]
  command = "" # No build command needed for JSON server
  functions = "functions-build" # Directory where Netlify Functions are built

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200