[build]
  command = "npm run build" # Build command for functions
  functions = "functions-build" # Directory for compiled Netlify Functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200