[build]
  command = "npm run build"
  publish = "public"          # Static site directory
  functions = "functions-build" # Compiled functions directory

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200